#!/usr/bin/env python3
"""Renders ledger/checkpoints/A7.md from the smoke harness's results.tsv and
findings.log. Invoked by tool/utopia_design_tools/smoke/run.sh; not meant to
be run standalone (though it is a plain, idempotent, argument-driven script).
"""
import argparse
import datetime
import os


def read_results(path):
    rows = []
    if not os.path.exists(path):
        return rows
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.rstrip("\n")
            if not line:
                continue
            # maxsplit=3 keeps any stray tabs inside the detail field itself,
            # so a row is dropped only when it has fewer than 4 tab-separated
            # fields to begin with (defensive: should not happen given
            # record_result() flattens newlines/tabs before writing).
            parts = line.split("\t", 3)
            if len(parts) != 4:
                continue
            item, check, status, detail = parts
            rows.append((item, check, status, detail))
    return rows


def read_findings(path):
    if not os.path.exists(path):
        return ""
    with open(path, "r", encoding="utf-8") as f:
        return f.read().strip()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", required=True)
    ap.add_argument("--findings", required=True)
    ap.add_argument("--step1", required=True)
    ap.add_argument("--step2", required=True)
    ap.add_argument("--step3", required=True)
    ap.add_argument("--step4", required=True)
    ap.add_argument("--artifacts-dir", required=True)
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    rows = read_results(args.results)
    findings = read_findings(args.findings)

    now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines = []
    lines.append("# A7 - end-to-end smoke harness results")
    lines.append("")
    lines.append(f"Generated by `tool/utopia_design_tools/smoke/run.sh` on {now}.")
    lines.append("")
    lines.append(
        "Deferred by charter amendment: checklist item 4 (custom-component loop) moves to "
        "A11. Item 6 (`--fix`) was implemented and committed ahead of this harness "
        "(commit 3a6a2d0); this harness exercises it as part of item 3's rebrand flow "
        "rather than re-implementing it. Item 7 (hook/fixture cross-check with B8): this "
        "harness owns the tools+twin+external-app surface only; B8's B8a/B8b slices "
        "already covered the skills-driven consumer flow on B's fixtures (see ledger/B.md "
        "B8 row) and are not duplicated here."
    )
    lines.append("")

    lines.append("## PASS/FAIL summary per checklist item")
    lines.append("")
    lines.append("| Item | Description | Status |")
    lines.append("|---|---|---|")
    lines.append(f"| 1 | in-repo tool pass (all 7 executables against the repo) | {args.step1} |")
    lines.append(f"| 2 | subprocess bin regression (7 bins x help/missing/malformed/invalid/json) | {args.step2} |")
    lines.append(f"| 3 | fresh external Flutter app end-to-end (bootstrap/rebrand/build/screenshot) | {args.step3} |")
    lines.append("| 4 | custom-component loop | DEFERRED to A11 (charter amendment) |")
    lines.append(f"| 5 | twin vs flutter hero side-by-sides | {args.step4} |")
    lines.append("| 6 | `--fix` derivation subset | DONE prior to this harness (commit 3a6a2d0); exercised in item 3 |")
    lines.append("| 7 | hook/fixture cross-check with B8 | not duplicated; B8a/B8b own the skills-driven flow |")
    lines.append("| 8 | record everything here | this file |")
    lines.append("")

    lines.append("## Detailed command/exit-code/artifact log")
    lines.append("")
    lines.append("Grouped by checklist item. Every row below is a single assertion the harness made against a real")
    lines.append("subprocess run; PASS means the assertion held, FAIL means it did not (see FINDINGS below for any")
    lines.append("that indicate a tool bug rather than a harness expectation problem).")
    lines.append("")

    by_item = {}
    for item, check, status, detail in rows:
        by_item.setdefault(item, []).append((check, status, detail))

    item_titles = {
        "1": "Item 1 - in-repo tool pass",
        "2": "Item 2 - subprocess bin regression",
        "3": "Item 3 - fresh external app end-to-end",
        "5": "Item 5 - twin vs flutter hero side-by-sides",
    }

    for item in ["1", "2", "3", "5"]:
        lines.append(f"### {item_titles[item]}")
        lines.append("")
        lines.append("| Check | Status | Detail |")
        lines.append("|---|---|---|")
        for check, status, detail in by_item.get(item, []):
            detail_escaped = detail.replace("|", "\\|").replace("\n", " ")
            if len(detail_escaped) > 300:
                detail_escaped = detail_escaped[:300] + "..."
            lines.append(f"| {check} | {status} | {detail_escaped} |")
        lines.append("")

    lines.append("## Retained artifacts")
    lines.append("")
    if os.path.isdir(args.artifacts_dir):
        for name in sorted(os.listdir(args.artifacts_dir)):
            full = os.path.join(args.artifacts_dir, name)
            size = os.path.getsize(full) if os.path.isfile(full) else 0
            lines.append(f"- `{full}` ({size} bytes)")
    else:
        lines.append("(artifacts directory not found)")
    lines.append("")

    lines.append("## FINDINGS (tool bugs surfaced by this harness, if any)")
    lines.append("")
    if findings:
        lines.append(findings)
    else:
        lines.append("None. Every FAIL row above (if any) reflects a harness assertion that did not hold; see the")
        lines.append("detail column for specifics. No tool defect was isolated during this run.")
    lines.append("")

    with open(args.out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
