/// Renders a [ThemeSpec] to deterministic Dart source text: a
/// `buildUtopiaTheme()` factory function assembling a `UtopiaThemeData` via
/// `UtopiaThemeData.fromTokens` plus a minimal `copyWith` for any semantic
/// slot whose resolved value differs from what `fromTokens` would compute.
///
/// This is the second of the two-layer design (protocol SPEC section 5):
/// `ThemeSpec.fromDocument` does all the DTCG/alias reasoning; this file only
/// prints already-resolved plain values, so it has no knowledge of the token
/// document shape at all.
library;

import 'package:dart_style/dart_style.dart';
import 'package:utopia_design_tools/src/dtcg/validator.dart' show protocolVersion;
import 'package:utopia_design_tools/src/theme_gen/theme_spec.dart';

/// The page width every generated file is formatted to, matching this
/// repo's `analysis_options.yaml` (`formatter: page_width: 120`).
const int _pageWidth = 120;

/// Dart-default ARGB32 values for `UtopiaThemeColors`' optional fields
/// (source: `lib/src/theme/utopia_theme_colors.dart` `@Default` values).
/// A generated theme omits an optional color argument when the resolved
/// value matches this table exactly, keeping canonical output minimal.
/// A drift between this table and the real defaults is caught by
/// `test/round_trip_test.dart` (the round-trip golden compiles against the
/// real `UtopiaThemeColors` and compares field-by-field).
const Map<String, int> dartDefaultOptionalColorArgb32 = {
  'onPrimary': 0xFFFFFFFF,
  'textBody': 0xFF5B6076,
  'surface': 0xFFFFFFFF,
  'border': 0xFFD8DCEB,
  'rowAlt': 0xFFF6F7FC,
  'hover': 0xFFEDF0FA,
  'chipBackground': 0xFFE9EDFD,
  'chipForeground': 0xFF3A4BCC,
  'hint': 0xFF6E748B,
  'shadow': 0xFF101828,
};

/// The Dart default for `UtopiaThemeData.tileHeight` (`@Default(58.0)`),
/// used to decide whether the generated `copyWith` needs a `tileHeight` arg.
const double dartDefaultTileHeight = 58.0;

/// Emits the full generated Dart source for [spec], read from an input
/// document originally read from [inputPath] (recorded in the header
/// comment for traceability).
///
/// [regeneratePath] is the input path as the tool was actually invoked with,
/// used for the copy-pasteable `Regenerate:` command line; it defaults to
/// [inputPath]. The two differ because [inputPath] is normalized to the
/// utopia_ui root so the identity header does not vary with the directory the
/// tool ran from - a stable identity, but not a path the printed command could
/// be run with from that directory.
///
/// The body is assembled without regard to line wrapping and then run through
/// `dart_style` at [_pageWidth] so output is canonical regardless of how the
/// emitter's own string-building happens to wrap things - this is what makes
/// the golden byte-compare stable.
String emitDart(ThemeSpec spec, {required String inputPath, String? regeneratePath}) {
  final header =
      '// GENERATED by utopia_design_tools:generate_theme from $inputPath - do not edit.\n'
      '// Regenerate: dart run utopia_design_tools:generate_theme ${regeneratePath ?? inputPath}\n';

  final buffer = StringBuffer();
  buffer.writeln("import 'package:flutter/widgets.dart';");
  buffer.writeln("import 'package:utopia_ui/utopia_ui.dart';");
  buffer.writeln();
  // The protocol version is the validator's single source of truth, not a
  // literal: a hand-maintained copy here silently outlived the 0.2.0 bump and
  // stamped every consumer's generated theme with a stale version.
  buffer.writeln('/// App theme built from the token document (protocol $protocolVersion).');
  buffer.writeln('UtopiaThemeData buildUtopiaTheme() {');
  buffer.writeln(_emitTokens(spec));
  buffer.writeln();
  buffer.writeln(_emitColors(spec.colors));
  buffer.writeln();
  buffer.writeln(_emitTextStyles(spec.textStyles));
  buffer.writeln();
  buffer.write(_emitReturn(spec));
  buffer.writeln('}');

  final formatted = DartFormatter(
    languageVersion: DartFormatter.latestLanguageVersion,
    pageWidth: _pageWidth,
  ).format(buffer.toString());

  // The formatter does not touch comments outside the formatted code, but we
  // keep the header as plain prepended text (not passed through the
  // formatter) so its wording is guaranteed byte-stable across dart_style
  // versions.
  return '$header$formatted';
}

// -------------------------------------------------------------------------
// tokens
// -------------------------------------------------------------------------

String _emitTokens(ThemeSpec spec) {
  final b = StringBuffer();
  b.writeln('  const tokens = UtopiaTokens(');
  b.writeln('    x: ${_num(spec.x)},');
  b.writeln('    spacing: UtopiaSpacingTokens(');
  b.writeln('      xxs: ${_num(spec.spacingXxs)},');
  b.writeln('      xs: ${_num(spec.spacingXs)},');
  b.writeln('      sm: ${_num(spec.spacingSm)},');
  b.writeln('      md: ${_num(spec.spacingMd)},');
  b.writeln('      lg: ${_num(spec.spacingLg)},');
  b.writeln('      xl: ${_num(spec.spacingXl)},');
  b.writeln('      xxl: ${_num(spec.spacingXxl)},');
  b.writeln('      xxxl: ${_num(spec.spacingXxxl)},');
  b.writeln('    ),');
  b.writeln('    radius: UtopiaRadiusTokens(');
  b.writeln('      xs: ${_num(spec.radiusXs)},');
  b.writeln('      sm: ${_num(spec.radiusSm)},');
  b.writeln('      md: ${_num(spec.radiusMd)},');
  b.writeln('      lg: ${_num(spec.radiusLg)},');
  b.writeln('      xl: ${_num(spec.radiusXl)},');
  b.writeln('      full: ${_num(spec.radiusFull)},');
  b.writeln('    ),');
  b.writeln('    borders: UtopiaBorderTokens(');
  b.writeln('      hairline: ${_num(spec.borderHairline)},');
  b.writeln('      thin: ${_num(spec.borderThin)},');
  b.writeln('      thick: ${_num(spec.borderThick)},');
  b.writeln('    ),');
  b.writeln('    shadows: UtopiaShadowTokens(');
  b.writeln('      sm: ${_shadowList(spec.shadowSm)},');
  b.writeln('      md: ${_shadowList(spec.shadowMd)},');
  b.writeln('      lg: ${_shadowList(spec.shadowLg)},');
  b.writeln('    ),');
  b.writeln('    fontWeights: UtopiaFontWeightTokens(');
  b.writeln('      regular: ${_fontWeight(spec.fontWeightRegular)},');
  b.writeln('      medium: ${_fontWeight(spec.fontWeightMedium)},');
  b.writeln('      semiBold: ${_fontWeight(spec.fontWeightSemiBold)},');
  b.writeln('      bold: ${_fontWeight(spec.fontWeightBold)},');
  b.writeln('    ),');
  b.writeln('    durations: UtopiaDurationTokens(');
  b.writeln('      xs: Duration(milliseconds: ${spec.durationXs}),');
  b.writeln('      sm: Duration(milliseconds: ${spec.durationSm}),');
  b.writeln('      md: Duration(milliseconds: ${spec.durationMd}),');
  b.writeln('      lg: Duration(milliseconds: ${spec.durationLg}),');
  b.writeln('      xl: Duration(milliseconds: ${spec.durationXl}),');
  b.writeln('    ),');
  b.writeln('    breakpoints: UtopiaBreakpointTokens(');
  b.writeln('      tabletMin: ${_num(spec.breakpointTabletMin)},');
  b.writeln('      webMin: ${_num(spec.breakpointWebMin)},');
  b.writeln('      sidebarMin: ${_num(spec.breakpointSidebarMin)},');
  b.writeln('    ),');
  b.write('  );');
  return b.toString();
}

String _shadowList(List<ResolvedShadowLayer> layers) {
  final items = layers.map(_shadowLayer).join(', ');
  return '[$items]';
}

String _shadowLayer(ResolvedShadowLayer layer) {
  final args = StringBuffer('color: ${_color(layer.color)}, blurRadius: ${_num(layer.blur)}');
  args.write(', offset: Offset(${_num(layer.offsetX)}, ${_num(layer.offsetY)})');
  if (layer.spread != 0) {
    args.write(', spreadRadius: ${_num(layer.spread)}');
  }
  return 'BoxShadow($args)';
}

// -------------------------------------------------------------------------
// colors
// -------------------------------------------------------------------------

String _emitColors(ResolvedThemeColors colors) {
  final b = StringBuffer();
  b.writeln('  final colors = UtopiaThemeColors(');
  b.writeln('    primary: ${_color(colors.primary)},');
  b.writeln('    accent: ${_color(colors.accent)},');
  b.writeln('    field: ${_color(colors.field)},');
  b.writeln('    canvas: ${_color(colors.canvas)},');
  b.writeln('    error: ${_color(colors.error)},');
  b.writeln('    disabled: ${_color(colors.disabled)},');
  b.writeln('    text: ${_color(colors.text)},');
  _emitOptionalColorOrSkip(b, 'onPrimary', colors.onPrimary);
  _emitOptionalColorOrSkip(b, 'textBody', colors.textBody);
  _emitOptionalColorOrSkip(b, 'shadow', colors.shadow);
  _emitOptionalColor(b, 'surface', colors.surface);
  _emitOptionalColor(b, 'border', colors.border);
  if (colors.divider != null) {
    b.writeln('    divider: ${_color(colors.divider!)},');
  }
  _emitOptionalColor(b, 'rowAlt', colors.rowAlt);
  _emitOptionalColor(b, 'hover', colors.hover);
  _emitOptionalColor(b, 'chipBackground', colors.chipBackground);
  _emitOptionalColor(b, 'chipForeground', colors.chipForeground);
  _emitOptionalColor(b, 'hint', colors.hint);
  b.writeln('    onColoredContent: ${_color(colors.onColoredContent)},');
  b.writeln('    onColoredSelected: ${_color(colors.onColoredSelected)},');
  b.writeln('    onColoredHover: ${_color(colors.onColoredHover)},');
  b.write('  );');
  return b.toString();
}

/// [_emitOptionalColor] for a token the document may not carry at all: a
/// document written against a protocol older than the token's introduction
/// resolves it to `null`, and the generated theme just omits the argument so
/// the Dart `@Default` applies.
void _emitOptionalColorOrSkip(StringBuffer b, String fieldName, ResolvedColor? resolved) {
  if (resolved == null) {
    return;
  }
  _emitOptionalColor(b, fieldName, resolved);
}

/// Emits an optional-color constructor argument only when [resolved] differs
/// from the Dart `@Default` for [fieldName] (see [dartDefaultOptionalColorArgb32]).
void _emitOptionalColor(StringBuffer b, String fieldName, ResolvedColor resolved) {
  final dartDefault = dartDefaultOptionalColorArgb32[fieldName];
  if (dartDefault != null && resolved.argb32 == dartDefault) {
    return;
  }
  b.writeln('    $fieldName: ${_color(resolved)},');
}

String _color(ResolvedColor color) {
  final hex = color.argb32.toRadixString(16).padLeft(8, '0').toUpperCase();
  return 'Color(0x$hex)';
}

// -------------------------------------------------------------------------
// text styles
// -------------------------------------------------------------------------

String _emitTextStyles(ResolvedThemeTextStyles textStyles) {
  final b = StringBuffer();
  b.writeln('  const textStyles = UtopiaThemeTextStyles(');
  b.writeln('    header: ${_textStyle(textStyles.header)},');
  b.writeln('    label: ${_textStyle(textStyles.label)},');
  b.writeln('    text: ${_textStyle(textStyles.text)},');
  b.writeln('    title: ${_textStyle(textStyles.title)},');
  b.writeln('    caption: ${_textStyle(textStyles.caption)},');
  b.writeln('    button: ${_textStyle(textStyles.button)},');
  b.write('  );');
  return b.toString();
}

String _textStyle(ResolvedTextStyle style) {
  final args = <String>['fontFamily: ${_dartString(style.fontFamily)}'];
  if (style.fontPackage != null) {
    args.add('package: ${_dartString(style.fontPackage!)}');
  }
  if (style.fontFamilyFallback.isNotEmpty) {
    final items = style.fontFamilyFallback.map(_dartString).join(', ');
    args.add('fontFamilyFallback: [$items]');
  }
  args.add('fontSize: ${_num(style.fontSize)}');
  args.add('fontWeight: ${_fontWeight(style.fontWeight)}');
  args.add('letterSpacing: ${_num(style.letterSpacing)}');
  args.add('color: ${_color(style.color)}');
  return 'TextStyle(${args.join(', ')})';
}

String _fontWeight(int weight) => 'FontWeight.w$weight';

/// Renders [value] as a single-quoted Dart string literal, escaping the
/// characters that would otherwise end the literal or start an interpolation
/// (`\`, `'`, `$`) plus newlines - font family and package names are free-form
/// strings from the token document, not identifiers.
String _dartString(String value) {
  final escaped = value
      .replaceAll(r'\', r'\\')
      .replaceAll("'", r"\'")
      .replaceAll(r'$', r'\$')
      .replaceAll('\r', r'\r')
      .replaceAll('\n', r'\n');
  return "'$escaped'";
}

// -------------------------------------------------------------------------
// final expression: fromTokens + minimal copyWith
// -------------------------------------------------------------------------

String _emitReturn(ThemeSpec spec) {
  final slots = spec.themeSlots;

  // Replicate UtopiaThemeData.fromTokens' arithmetic on the resolved spec so
  // we can tell exactly which slots a copyWith needs to override (protocol
  // SPEC section 5 / A6-spec.md "fromTokens arithmetic").
  final derivedBorderRadius = spec.radiusLg;
  final derivedCardRadius = spec.radiusXl;
  final derivedFieldContentPaddingTop = spec.x * 2;
  final derivedFieldContentPaddingBottom = spec.x * 1;
  final derivedFieldContentPaddingLeft = spec.spacingLg;
  final derivedFieldContentPaddingRight = spec.spacingLg;
  final derivedFieldMinHeight = spec.x * 8.5;
  final derivedPageTopPadding = spec.spacingXxxl;
  const derivedTileHeight = dartDefaultTileHeight;

  final copyWithArgs = <String>[];

  final borderRadiusDiffers = slots.borderRadius != derivedBorderRadius;
  final cardRadiusDiffers = slots.cardRadius != derivedCardRadius;
  final fieldContentPaddingDiffers =
      slots.fieldContentPaddingTop != derivedFieldContentPaddingTop ||
      slots.fieldContentPaddingRight != derivedFieldContentPaddingRight ||
      slots.fieldContentPaddingBottom != derivedFieldContentPaddingBottom ||
      slots.fieldContentPaddingLeft != derivedFieldContentPaddingLeft;
  final fieldMinHeightDiffers = slots.fieldMinHeight != derivedFieldMinHeight;
  final pageTopPaddingDiffers = slots.pageTopPadding != derivedPageTopPadding;
  final tileHeightDiffers = slots.tileHeight != derivedTileHeight;

  if (borderRadiusDiffers) {
    copyWithArgs.add('borderRadius: BorderRadius.all(Radius.circular(${_num(slots.borderRadius)}))');
  }
  if (cardRadiusDiffers) {
    copyWithArgs.add('cardRadius: BorderRadius.all(Radius.circular(${_num(slots.cardRadius)}))');
  }
  if (fieldContentPaddingDiffers) {
    copyWithArgs.add(
      'fieldContentPadding: EdgeInsets.fromLTRB(${_num(slots.fieldContentPaddingLeft)}, '
      '${_num(slots.fieldContentPaddingTop)}, ${_num(slots.fieldContentPaddingRight)}, '
      '${_num(slots.fieldContentPaddingBottom)})',
    );
  }
  if (fieldMinHeightDiffers) {
    copyWithArgs.add('fieldMinHeight: ${_num(slots.fieldMinHeight)}');
  }
  if (pageTopPaddingDiffers) {
    copyWithArgs.add('pageTopPadding: ${_num(slots.pageTopPadding)}');
  }
  if (tileHeightDiffers) {
    copyWithArgs.add('tileHeight: ${_num(slots.tileHeight)}');
  }

  final b = StringBuffer();
  b.writeln('  final theme = UtopiaThemeData.fromTokens(tokens: tokens, colors: colors, textStyles: textStyles);');
  if (copyWithArgs.isEmpty) {
    b.writeln('  return theme;');
  } else {
    b.writeln('  return theme.copyWith(');
    for (final arg in copyWithArgs) {
      b.writeln('    $arg,');
    }
    b.writeln('  );');
  }
  return b.toString();
}

// -------------------------------------------------------------------------
// number formatting
// -------------------------------------------------------------------------

/// Formats a resolved double as Dart source: whole values print without a
/// trailing `.0` (`4` not `4.0`); fractional values print as-is (`1.5`).
String _num(double value) {
  if (value == value.roundToDouble() && value.isFinite) {
    return value.toInt().toString();
  }
  return value.toString();
}
