// GENERATED by utopia_design_tools:generate_theme from ../../tokens/utopia.tokens.json - do not edit.
// Regenerate: dart run utopia_design_tools:generate_theme ../../tokens/utopia.tokens.json
import 'package:flutter/widgets.dart';
import 'package:utopia_ui/utopia_ui.dart';

/// App theme built from the token document (protocol 0.1.0).
UtopiaThemeData buildUtopiaTheme() {
  const tokens = UtopiaTokens(
    x: 4,
    spacing: UtopiaSpacingTokens(xxs: 2, xs: 4, sm: 8, md: 12, lg: 16, xl: 24, xxl: 32, xxxl: 48),
    radius: UtopiaRadiusTokens(xs: 4, sm: 6, md: 8, lg: 12, xl: 16, full: 9999),
    borders: UtopiaBorderTokens(hairline: 1, thin: 1.5, thick: 2),
    shadows: UtopiaShadowTokens(
      sm: [BoxShadow(color: Color(0x0D000000), blurRadius: 6, offset: Offset(0, 1))],
      md: [BoxShadow(color: Color(0x26000000), blurRadius: 10, offset: Offset(0, 2))],
      lg: [BoxShadow(color: Color(0x59000000), blurRadius: 14, offset: Offset(3, 3))],
    ),
    fontWeights: UtopiaFontWeightTokens(
      regular: FontWeight.w400,
      medium: FontWeight.w500,
      semiBold: FontWeight.w600,
      bold: FontWeight.w700,
    ),
    durations: UtopiaDurationTokens(
      xs: Duration(milliseconds: 100),
      sm: Duration(milliseconds: 150),
      md: Duration(milliseconds: 200),
      lg: Duration(milliseconds: 300),
      xl: Duration(milliseconds: 400),
    ),
    breakpoints: UtopiaBreakpointTokens(tabletMin: 600, webMin: 900, sidebarMin: 1000),
  );

  final colors = UtopiaThemeColors(
    primary: Color(0xFF536DFE),
    accent: Color(0xFF536DFE),
    field: Color(0xFFEDEDED),
    canvas: Color(0xFFF5F5F5),
    error: Color(0xFFFF5252),
    disabled: Color(0xFFBDBDBD),
    text: Color(0xDD000000),
    onColoredContent: Color(0xD9FFFFFF),
    onColoredSelected: Color(0x2EFFFFFF),
    onColoredHover: Color(0x14FFFFFF),
  );

  const textStyles = UtopiaThemeTextStyles(
    header: TextStyle(
      fontFamily: 'Sora',
      package: 'utopia_ui',
      fontSize: 24,
      fontWeight: FontWeight.w600,
      letterSpacing: 1,
      color: Color(0xDD000000),
    ),
    label: TextStyle(
      fontFamily: 'Sora',
      package: 'utopia_ui',
      fontSize: 12,
      fontWeight: FontWeight.w600,
      letterSpacing: 1,
      color: Color(0xDD000000),
    ),
    text: TextStyle(
      fontFamily: 'Sora',
      package: 'utopia_ui',
      fontSize: 12,
      fontWeight: FontWeight.w600,
      letterSpacing: 1,
      color: Color(0xDD000000),
    ),
    title: TextStyle(
      fontFamily: 'Sora',
      package: 'utopia_ui',
      fontSize: 16,
      fontWeight: FontWeight.w600,
      letterSpacing: 1,
      color: Color(0xDD000000),
    ),
    caption: TextStyle(
      fontFamily: 'Sora',
      package: 'utopia_ui',
      fontSize: 10,
      fontWeight: FontWeight.w600,
      letterSpacing: 1,
      color: Color(0xDD000000),
    ),
    button: TextStyle(
      fontFamily: 'Sora',
      package: 'utopia_ui',
      fontSize: 12,
      fontWeight: FontWeight.w600,
      letterSpacing: 1,
      color: Color(0xFFFFFFFF),
    ),
  );

  final theme = UtopiaThemeData.fromTokens(tokens: tokens, colors: colors, textStyles: textStyles);
  return theme;
}
