// Golden-line and behavior tests for the generate_twin generators (protocol
// SPEC section 4; see ledger/checkpoints/A4-spec.md): spot-assert exact CSS
// lines for representative tokens rather than full-file byte compares (the
// canonical export can gain tokens over time), plus the DESIGN.md front
// matter splice contract and idempotence of every generator.
import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:path/path.dart' as p;
import 'package:utopia_design_tools/src/dtcg/token_document.dart';
import 'package:utopia_design_tools/src/twin/css_generator.dart';
import 'package:utopia_design_tools/src/twin/design_md_generator.dart';
import 'package:utopia_design_tools/src/twin/tailwind_generator.dart';

void main() {
  final repoRoot = Directory(p.normalize(p.join(Directory.current.path, '..', '..')));
  final canonicalTokensFile = File(p.join(repoRoot.path, 'tokens', 'utopia.tokens.json'));

  Map<String, dynamic> loadCanonical() => jsonDecode(canonicalTokensFile.readAsStringSync()) as Map<String, dynamic>;

  TokenDocument canonicalDocument() => TokenDocument.parse(loadCanonical());

  group('cssVarName', () {
    test('kebab-cases camelCase path segments and joins with -', () {
      expect(cssVarName('spacing.md'), equals('--utopia-spacing-md'));
      expect(cssVarName('fontWeight.semiBold'), equals('--utopia-font-weight-semi-bold'));
      expect(
        cssVarName('theme.fieldContentPadding.top'),
        equals('--utopia-theme-field-content-padding-top'),
      );
      expect(cssVarName('breakpoint.tablet'), equals('--utopia-breakpoint-tablet'));
    });
  });

  group('generateCss golden lines', () {
    test('spacing.md', () {
      final css = generateCss(canonicalDocument(), inputPath: 'tokens/utopia.tokens.json', profileVersion: '0.2.0');
      expect(css, contains('  --utopia-spacing-md: 12px;'));
    });

    test('fontWeight.semiBold', () {
      final css = generateCss(canonicalDocument(), inputPath: 'tokens/utopia.tokens.json', profileVersion: '0.2.0');
      expect(css, contains('  --utopia-font-weight-semi-bold: 600;'));
    });

    test('theme.borderRadius emits a var() alias reference', () {
      final css = generateCss(canonicalDocument(), inputPath: 'tokens/utopia.tokens.json', profileVersion: '0.2.0');
      expect(css, contains('  --utopia-theme-border-radius: var(--utopia-radius-sm);'));
    });

    test('shadow.sm emits the full box-shadow value with unitless zero components', () {
      final css = generateCss(canonicalDocument(), inputPath: 'tokens/utopia.tokens.json', profileVersion: '0.2.0');
      expect(css, contains('  --utopia-shadow-sm: 0 1px 6px 0 rgb(0 0 0 / 0.051);'));
    });

    test('textStyle.header expands to per-property vars with the folded sibling color', () {
      final css = generateCss(canonicalDocument(), inputPath: 'tokens/utopia.tokens.json', profileVersion: '0.2.0');
      expect(css, contains('  --utopia-text-style-header-font-family: Sora;'));
      expect(css, contains('  --utopia-text-style-header-font-size: 24px;'));
      expect(css, contains('  --utopia-text-style-header-font-weight: 600;'));
      expect(css, contains('  --utopia-text-style-header-letter-spacing: 1px;'));
      // The fold rule: textStyle-colors.header -> ...-header-color, NOT
      // ...-text-style-colors-header.
      expect(css, contains('  --utopia-text-style-header-color: rgb(0 0 0 / 0.8667);'));
      expect(css, isNot(contains('text-style-colors')));
    });

    test('x is unitless', () {
      final css = generateCss(canonicalDocument(), inputPath: 'tokens/utopia.tokens.json', profileVersion: '0.2.0');
      expect(css, contains('  --utopia-x: 4;'));
    });

    test('an alpha color renders rgb() with 0-255 channels and trimmed alpha', () {
      final css = generateCss(canonicalDocument(), inputPath: 'tokens/utopia.tokens.json', profileVersion: '0.2.0');
      // color.text: components [0,0,0], alpha 0.866667 -> rgb(0 0 0 / 0.8667).
      expect(css, contains('  --utopia-color-text: rgb(0 0 0 / 0.8667);'));
    });

    test('an opaque color renders lowercase hex', () {
      final css = generateCss(canonicalDocument(), inputPath: 'tokens/utopia.tokens.json', profileVersion: '0.2.0');
      expect(css, contains('  --utopia-color-primary: #536dfe;'));
    });

    test('header comment carries the input path and regeneration command', () {
      final css = generateCss(canonicalDocument(), inputPath: 'tokens/utopia.tokens.json', profileVersion: '0.2.0');
      expect(
        css,
        contains('/* GENERATED by utopia_design_tools:generate_twin from tokens/utopia.tokens.json - do not edit. */'),
      );
      expect(
        css,
        contains('/* Regenerate: dart run utopia_design_tools:generate_twin tokens/utopia.tokens.json */'),
      );
      expect(css, contains('/* profileVersion: 0.2.0 */'));
    });

    test('is idempotent: generating twice from the same input produces identical bytes', () {
      final first = generateCss(canonicalDocument(), inputPath: 'tokens/utopia.tokens.json', profileVersion: '0.2.0');
      final second = generateCss(
        canonicalDocument(),
        inputPath: 'tokens/utopia.tokens.json',
        profileVersion: '0.2.0',
      );
      expect(first, equals(second));
    });
  });

  group('generateTailwind golden lines', () {
    test('maps color/spacing/radius/shadow/fontWeight/breakpoint families per the SPEC table', () {
      final tailwind = generateTailwind(
        canonicalDocument(),
        inputPath: 'tokens/utopia.tokens.json',
        profileVersion: '0.2.0',
      );
      expect(tailwind, contains('  --color-primary: #536dfe;'));
      expect(tailwind, contains('  --spacing-md: 12px;'));
      expect(tailwind, contains('  --radius-sm: 6px;'));
      expect(tailwind, contains('  --shadow-sm: 0 1px 6px 0 rgb(0 0 0 / 0.051);'));
      expect(tailwind, contains('  --font-weight-semi-bold: 600;'));
      expect(tailwind, contains('  --breakpoint-tablet: 600px;'));
      expect(tailwind, contains('  --font-header: Sora;'));
      expect(tailwind, contains('  --color-text-style-header: rgb(0 0 0 / 0.8667);'));
    });

    test('families with no stable namespace are kept as comments, not dropped', () {
      final tailwind = generateTailwind(
        canonicalDocument(),
        inputPath: 'tokens/utopia.tokens.json',
        profileVersion: '0.2.0',
      );
      expect(tailwind, contains('  /* --utopia-x: 4; */'));
      expect(tailwind, contains('  /* --utopia-border-hairline: 1px; */'));
      expect(tailwind, contains('  /* --utopia-duration-md: 200ms; */'));
      expect(tailwind, contains('  /* --utopia-theme-border-radius: 6px; */'));
    });

    test('is idempotent', () {
      final first = generateTailwind(
        canonicalDocument(),
        inputPath: 'tokens/utopia.tokens.json',
        profileVersion: '0.2.0',
      );
      final second = generateTailwind(
        canonicalDocument(),
        inputPath: 'tokens/utopia.tokens.json',
        profileVersion: '0.2.0',
      );
      expect(first, equals(second));
    });
  });

  group('DESIGN.md front matter', () {
    test('emits name, colors, typography, rounded and spacing per SPEC 4.6', () {
      final frontMatter = buildFrontMatterBody(canonicalDocument());
      expect(frontMatter, contains('name: Utopia'));
      expect(frontMatter, contains('  primary: "#536dfe"'));
      expect(frontMatter, contains('    fontFamily: "Sora"'));
      expect(frontMatter, contains('    fontSize: "24px"'));
      expect(frontMatter, contains('    fontWeight: 600'));
      expect(frontMatter, contains('  sm: "6px"')); // rounded.sm
      expect(frontMatter, contains('  md: "12px"')); // spacing.md
    });

    test('is idempotent', () {
      final first = buildFrontMatterBody(canonicalDocument());
      final second = buildFrontMatterBody(canonicalDocument());
      expect(first, equals(second));
    });

    test('splice preserves a doctored body byte-for-byte', () {
      final frontMatter = buildFrontMatterBody(canonicalDocument());
      const doctoredBody = '''
## Overview

A hand-edited paragraph a maintainer wrote after the skeleton was generated,
with trailing whitespace and unusual   spacing preserved.

## Colors

Some more hand-written prose that must survive regeneration untouched.
''';
      final original = '---\nname: Utopia\ncolors:\n  primary: "#000000"\n---\n$doctoredBody';

      final spliced = spliceDesignMd(original, frontMatter).content;

      expect(spliced, contains(doctoredBody));
      expect(spliced, isNot(contains('primary: "#000000"')));
      expect(spliced, contains('primary: "#536dfe"'));

      // Regenerating again with an unrelated front matter body must not
      // disturb the body a second time.
      final splicedAgain = spliceDesignMd(spliced, frontMatter).content;
      expect(splicedAgain, equals(spliced));
    });

    test('missing closing marker preserves the hand-authored body and warns', () {
      final frontMatter = buildFrontMatterBody(canonicalDocument());
      const realBody = '## Overview\n\nHand-written prose whose closing marker got lost in a bad merge.\n';
      const malformed = '---\nname: Utopia\ncolors:\n  primary: "#000000"\n$realBody';

      final splice = spliceDesignMd(malformed, frontMatter);

      expect(splice.content, contains(realBody), reason: 'the body must never be discarded');
      expect(splice.warning, isNotNull);
      expect(splice.warning, contains('no closing'));
    });

    test('content without front matter is kept entirely as body, with a warning', () {
      final frontMatter = buildFrontMatterBody(canonicalDocument());
      const bareBody = '## Overview\n\nProse that never had front matter.\n';

      final splice = spliceDesignMd(bareBody, frontMatter);

      expect(splice.content, contains(bareBody));
      expect(splice.content, startsWith('---\nname: Utopia\n'));
      expect(splice.warning, isNotNull);
    });

    test('writes front matter plus the full skeleton body when the file is absent', () {
      final frontMatter = buildFrontMatterBody(canonicalDocument());
      final result = spliceDesignMd(null, frontMatter).content;

      expect(result, startsWith('---\nname: Utopia\n'));
      expect(result, contains(designMdSkeletonBody));
      expect(result, contains('## Overview'));
      expect(result, contains("## Do's and Don'ts"));
    });
  });
}
